export const ROUTER = {
  AUTH: "/",
  USERS: "users",
  STATISTICS: "statistics",
  GENERAL: "general",
  CREATE: "create",
  TRADE: "trade",
  PORTAL: "portal-users",
  PORTALS: "portals",
  PROVIDED: "provided",
  AVAILABLE: "available",
  STABILITY: "stability",
  UTILIZATION: "utilization",
  ADDITION: "addition",
  EDIT: "edit/:id",
};
