export const dataLabels = [
    { value: "guruch", label: "Guruch" },
    { value: "arpa", label: "Arpa" },
    { value: "bugdoy", label: "Bug'doy" },
    { value: "makkajoxori", label: "Makkajo'xori" },
    { value: "yuqori_navli_bugdoy_uni", label: "Yuqori navli bug'doy uni" },
    { value: "birinchi_navli_bugdoy_uni", label: "Birinchi navli bug'doy uni" },
    {
      value: "1_navli_undan_tayyorlangan_bugdoy_noni",
      label: "1-navli undan tayyorlangan bug'doy noni",
    },
    { value: "mol_goshti", label: "Mol go'shti" },
    { value: "qoy_goshti", label: "Qo'y go'shti" },
    { value: "parrandachilik", label: "Tovuq go'shti" },
    { value: "barcha_turdagi_baliqlar", label: "Barcha turdagi baliqlar" },
    { value: "yangi_sut", label: "Yangi sut (1 litr)" },
    { value: "tuxum", label: "Tuxum (10 dona)" },
    { value: "paxta_yogi", label: "Paxta yog'i (1 litr)" },
    { value: "kungaboqar", label: "Kungaboqar yog'i (1 litr)" },
    { value: "sariyog", label: "Sariyog'" },
    { value: "limon", label: "Limon" },
    { value: "olma", label: "Olma" },
    { value: "nok", label: "Nok" },
    { value: "uzum", label: "Uzum" },
    { value: "tarvuz", label: "Tarvuz" },
    { value: "qovun", label: "Qovun" },
    { value: "kishmish", label: "Kishmish" },
    { value: "karam", label: "Karam" },
    { value: "bodring", label: "Bodring" },
    { value: "pomidor", label: "Pomidor" },
    { value: "baqlajon", label: "Baqlajon" },
    { value: "bolgar_qalampiri", label: "Bolgar qalampiri" },
    { value: "qovoq", label: "Qovoq" },
    { value: "sabzi", label: "Sabzi" },
    { value: "sarimsoq", label: "Sarimsoq" },
    { value: "piyoz", label: "Piyoz" },
    { value: "kartoshka", label: "Kartoshka" },
    { value: "loviya", label: "Loviya" },
    { value: "noxat", label: "No'xat" },
    { value: "mosh", label: "Mosh" },
    { value: "shakar", label: "Shakar" },
  ];